// Package models of db entity
// Code generated by go-god/tbox. DO NOT EDIT!!!

package models

import (
	"time"
)

// UserInfoTable for user_info
const UserInfoTable = "user_info"

// UserInfoEntity for user_info table entity struct.
type UserInfoEntity struct {
	ID	int64	`db:"id"`
	CreatedAt	*time.Time	`db:"created_at"`
	UpdatedAt	*time.Time	`db:"updated_at"`
	DeletedAt	*time.Time	`db:"deleted_at"`
	UserCode	string	`db:"user_code"`
	NickName	string	`db:"nick_name"`
	Birthday	string	`db:"birthday"`
	Sex	int64	`db:"sex"`
	Icon	string	`db:"icon"`
	RealIcon	string	`db:"real_icon"`
	Job	string	`db:"job"`
	Weight	string	`db:"weight"`
	Height	string	`db:"height"`
	Income	string	`db:"income"`
	Hometown	string	`db:"hometown"`
	Desc	string	`db:"desc"`
	IsShow	int64	`db:"is_show"`
	Status	int64	`db:"status"`
	City	string	`db:"city"`
	Province	string	`db:"province"`
	IsComplete	int64	`db:"is_complete"`
	IsReal	int64	`db:"is_real"`
	IsSelf	int64	`db:"is_self"`
	IsHightEducated	int64	`db:"is_hight_educated"`
	IsStudent	int64	`db:"is_student"`
	IsNymph	int64	`db:"is_nymph"`
	FromChannel	string	`db:"from_channel"`
	FromVersion	string	`db:"from_version"`
	Recommend	int64	`db:"recommend"`
	OnlineStatus	int64	`db:"online_status"`
	IsVip	int64	`db:"is_vip"`
	LocationSource	int64	`db:"location_source"`
	IsShowFromType	int64	`db:"is_show_from_type"`
	EmotionalState	string	`db:"emotional_state"`
	UserTag	string	`db:"user_tag"`
}
